### ISSUE TITLE
Additions to NBTUtils

### ISSUE THREAD

**Issue by ItzGuy** [DirtyConcept/Espresso#4]
Methods:
- getTag
- clearTags
- containsTag
- getAllTags

**Comment by SadGhostYT** [comment]
Thank you for opening this issue, @ItzGuy.

I appreciate your interest in improving NBTUtils. The methods you mentioned, such as `getTag`, `clearTags`, `containsTag`, and `getAllTags`, sound like valuable additions to the library.

I'm glad to inform you that I will be implementing these methods in the next release of NBTUtils. They will provide convenient functionality for retrieving tags, clearing tags, checking for tag existence, and retrieving all tags.

Your contribution is greatly appreciated, and I look forward to delivering these enhancements in the upcoming release. If you have any further suggestions or feedback, please don't hesitate to let me know.

Thank you again for your valuable input.
